language: node_js
node_js:
  - "8"
script:
  - echo 'Build starts!!'
  - echo 'Installing Deps!'
  - yarn
  - echo 'Testing!'
  - npm run test
branches:
  only: 
    - gh-pages
after_success:
  - npm run delpoy
  - npm run lh -- http://aamitsharma2705.github.io/lighthouseintegration